package com.az.manager.pojo.po;

public class TbManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.id
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.name
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.password
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.age
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.sex
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.nickname
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.usertype
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    private Integer usertype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.id
     *
     * @return the value of tb_manager.id
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.id
     *
     * @param id the value for tb_manager.id
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.name
     *
     * @return the value of tb_manager.name
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.name
     *
     * @param name the value for tb_manager.name
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.password
     *
     * @return the value of tb_manager.password
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.password
     *
     * @param password the value for tb_manager.password
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.age
     *
     * @return the value of tb_manager.age
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.age
     *
     * @param age the value for tb_manager.age
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.sex
     *
     * @return the value of tb_manager.sex
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.sex
     *
     * @param sex the value for tb_manager.sex
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.nickname
     *
     * @return the value of tb_manager.nickname
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.nickname
     *
     * @param nickname the value for tb_manager.nickname
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.usertype
     *
     * @return the value of tb_manager.usertype
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    public Integer getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.usertype
     *
     * @param usertype the value for tb_manager.usertype
     *
     * @mbggenerated Thu Nov 08 09:49:11 CST 2018
     */
    public void setUsertype(Integer usertype) {
        this.usertype = usertype;
    }
}